//---------------------------------------------------------------------
// tb_top_cfg.v — parameterized config sweep (VP-TOP-015, REQ-022)
// Project  : rinriAI (PRJ-005)
// Language : pure Verilog-2001, iverilog -g2001 -Wall
// DUT      : learn_accel at any FEATURES x HIDDEN x CLASSES (default 8x4x3;
//            override with -DCFG_F=784 -DCFG_H=32 -DCFG_C=10 -DCFG_LR=2)
// Golden   : vectors generated by verify/scripts/gen_vectors.py into
//            verify/golden/<tag>/ (tag = cfg_<F>x<H>x<C>_s<N>)
// Checks   : elaboration clean + bit-exact golden replay (per-sample
//            PRED/counters + final weights) at the given config.
//---------------------------------------------------------------------
`timescale 1ns / 1ps
`default_nettype none

`ifndef CFG_F
`define CFG_F 8
`endif
`ifndef CFG_H
`define CFG_H 4
`endif
`ifndef CFG_C
`define CFG_C 3
`endif
`ifndef CFG_LR
`define CFG_LR 0
`endif
`ifndef CFG_N
`define CFG_N 16
`endif
// vector paths: switch with -DCFG_BIG for the 784/32/10 run
`ifdef CFG_BIG
`define CFG_STIM "verify/golden/cfg_784x32x10/stimulus.hex"
`define CFG_EXP  "verify/golden/cfg_784x32x10/expected.hex"
`define CFG_FEXP "verify/golden/cfg_784x32x10_freeze/expected.hex"
`else
`define CFG_STIM "verify/golden/cfg_8x4x3/stimulus.hex"
`define CFG_EXP  "verify/golden/cfg_8x4x3/expected.hex"
`define CFG_FEXP "verify/golden/cfg_8x4x3_freeze/expected.hex"
`endif

module tb_top_cfg;
    localparam FEATURES = `CFG_F;
    localparam HIDDEN   = `CFG_H;
    localparam CLASSES  = `CFG_C;
    localparam LR_SHIFT = `CFG_LR;
    localparam N_SAMPLES = `CFG_N;
    localparam W_TOT = FEATURES*HIDDEN + HIDDEN + HIDDEN*CLASSES + CLASSES;
    localparam STIM_WORDS = W_TOT + N_SAMPLES*(FEATURES+1);
    localparam EXP_WORDS  = N_SAMPLES*5 + W_TOT;

    reg clk_core = 1'b0;
    reg rst_n    = 1'b0;
    reg        apb_psel = 0, apb_penable = 0, apb_pwrite = 0;
    reg  [31:0] apb_paddr = 0, apb_pwdata = 0;
    wire [31:0] apb_prdata;
    wire        apb_pready, apb_pslverr;
    reg        s_valid = 0, s_last = 0;
    reg  [7:0] s_data = 0;
    wire       s_ready;

    integer errors = 0;
    reg [31:0] stim [0:STIM_WORDS-1];
    reg [31:0] exp  [0:EXP_WORDS-1];
    reg [31:0] rd;

    learn_accel #(.FEATURES(FEATURES), .HIDDEN(HIDDEN), .CLASSES(CLASSES)) dut (
        .clk_core (clk_core), .rst_n (rst_n),
        .psel (apb_psel), .penable (apb_penable), .pwrite (apb_pwrite),
        .paddr (apb_paddr), .pwdata (apb_pwdata), .prdata (apb_prdata),
        .pready (apb_pready), .pslverr (apb_pslverr),
        .s_valid (s_valid), .s_ready (s_ready), .s_data (s_data), .s_last (s_last)
    );

    `include "tb_common/clk_rst.vh"
    `include "tb_common/checker.vh"
    `include "tb_common/apb4_bfm.vh"
    `include "tb_common/stream_byte.vh"
    `include "tb_common/golden_replay.vh"

    // ---------------------------------------------------------------
    initial begin
        $display("CONFIG: FEATURES=%0d HIDDEN=%0d CLASSES=%0d lr_shift=%0d samples=%0d W_TOT=%0d",
                 FEATURES, HIDDEN, CLASSES, LR_SHIFT, N_SAMPLES, W_TOT);
`ifndef CFG_BIG
        $dumpfile("tb_top_cfg.vcd");
        $dumpvars(0, tb_top_cfg);
`endif

        $readmemh(`CFG_STIM, stim);
        $readmemh(`CFG_EXP,  exp);

        tb_reset;
        golden_replay(1'b0, 1'b0, LR_SHIFT[3:0]);   // step mode, train
        $display("-- cfg replay done --");
        $readmemh(`CFG_FEXP, exp);                  // freeze-expected data
        golden_replay(1'b0, 1'b1, LR_SHIFT[3:0]);   // freeze mode
        $display("-- cfg freeze replay done --");

        test_summary("tb_top_cfg");
        $finish;
    end

    initial begin #300_000_000; $display("TEST FAILED: timeout tb_top_cfg"); $finish; end
endmodule

`default_nettype wire
